### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DanudeSandstorm** [Mimickal/Floodgate#2]
- [ ] Toggle power states
- - [x] GUI button in the menu with "ON", "OFF", and "REDSTONE"
- - [ ] TileEntity functionality for only outputting when redstone powered
- [ ] Add fluid via GUI using buckets/IC2 fluid cells
- - [x] Bucket/fluid cell input area
- - - [x] GUI Slot
- - - [ ] TileEntity take bucket/fluid cell water amount
- - [x] Empty container output
- - - [x] GUI Slot
- - - [ ] TileEntity after draining input, place empty bucket/fluid cell
- [ ] Tank GUI (Readout for current fluid amount)
- - [ ] GUI Render water level
- - [x] Tooltip water amount
- - [ ] Figure out what getTankInfoMapper actually does
- [ ] Only accept pipe input connection on the top
- [ ] Right click with full bucket to place MATCHING liquid (liquid in tank)

**Comment by DanudeSandstorm** [comment]
Setup:
https://mcforge.readthedocs.io/en/latest/gettingstarted/

Gui:
https://www.youtube.com/watch?v=B4HWFG8VJM0
https://github.com/CJMinecraft01/BitOfEverything/tree/master/src/main/java/cjminecraft/bitofeverything
https://github.com/CJMinecraft01/CJCore/tree/master/src/main/java/cjminecraft/core

Saving Block States:
https://mcforge.readthedocs.io/en/latest/blockstates/states/
https://mcforge.readthedocs.io/en/latest/datastorage/extendedentityproperties/

Custom Gui Buttons:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2172022-how-to-add-a-button-to-a-gui
http://www.minecraftforge.net/forum/topic/27964-18-custom-gui-with-textured-buttons-and-scrollpanes/
http://www.minecraftforge.net/forum/topic/1728-gui-functions/

ItemHandler/Slots:
http://www.minecraftforge.net/forum/topic/43335-110-itemhandler-output-slots/
http://www.minecraftforge.net/forum/topic/41823-110-capabilities/
http://www.minecraftforge.net/forum/topic/44975-item-with-iitemhandler-capability/ *

Block With GUI That Processes Instantly:
http://jabelarminecraft.blogspot.com/p/blog-page_31.html *
